spring:
  freemarker:
    prefix: /
    suffix: .ftl
    enabled: true

  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC

  mvc:
    static-path-pattern: /static/**

server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  #mapper文件的加载地址 在resources文件下
  mapper-locations: classpath:/mybatis/*.xml
  #起别名 扫描包
  type-aliases-package: com.example.community.demo/entity

